<a href="https://colab.research.google.com/github/wolfiee42/PyTorch-for-DeepLearning/blob/main/Building%20neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import torch.nn as nn


# Create input tensor: 1 sample with 3 features
input_tensor = torch.tensor([[0.5, 0.8, 0.2]])
print("Input Shape:", input_tensor.shape) # torch.Size([1, 3])


# Create a linear layer: 3 inputs -> 2 outputs
linear_layer = nn.Linear(in_features=3, out_features=2)


# Access weights
print("Weight Shape:", linear_layer.weight.shape)
print("Weight:\n", linear_layer.weight)


# Access bias
print("\nBias Shape:", linear_layer.bias.shape)
print("Bias:", linear_layer.bias)


# Pass input through the layer
output = linear_layer(input_tensor)
print("output shape:", output.shape)  # torch.Size([1, 2])
print("Output:", output)

Input Shape: torch.Size([1, 3])
Weight Shape: torch.Size([2, 3])
Weight:
 Parameter containing:
tensor([[-0.4873,  0.4067,  0.5264],
        [-0.0965,  0.1631, -0.3544]], requires_grad=True)

Bias Shape: torch.Size([2])
Bias: Parameter containing:
tensor([0.2879, 0.5285], requires_grad=True)
output shape: torch.Size([1, 2])
Output: tensor([[0.4749, 0.5398]], grad_fn=<AddmmBackward0>)


In [15]:
import torch
import torch.nn as nn

layer1 = nn.Linear(3, 2)
layer2 = nn.Linear(3, 2)

print("Layer 1 weights:\n", layer1.weight.data)
print("Layer 2 weights:\n", layer2.weight.data)
print("\nWeights are different:", not torch.equal(layer1.weight, layer2.weight))



Layer 1 weights:
 tensor([[ 0.2848, -0.2819, -0.0102],
        [ 0.0460, -0.3233, -0.2109]])
Layer 2 weights:
 tensor([[ 0.4225, -0.3504,  0.3498],
        [-0.5711, -0.1747,  0.2493]])

Weights are different: True


In [18]:
import torch
import torch.nn as nn


# Weather data: [temperature, humidity, wind_speed]
# Values are normalized (scaled between 0 and 1)
weather_data = torch.tensor([[0.5, 0.8, 0.2]])  # Hot, very humid, light wind

print("Input (weather features):", weather_data)
print("Shape:", weather_data.shape)


# Create network: 3 features -> 2 predictions
weathear_network = nn.Linear(in_features=3, out_features=2)


# Make prediction
prediction = weathear_network(weather_data)
print("\nRaw prediction (rain, clouds):", prediction)

Input (weather features): tensor([[0.5000, 0.8000, 0.2000]])
Shape: torch.Size([1, 3])

Raw prediction (rain, clouds): tensor([[0.2770, 0.7079]], grad_fn=<AddmmBackward0>)


In [22]:
import torch
import torch.nn as nn

torch.manual_seed(123)

# Step 1: Create input data (3 samples, 4 features each)
input_data = torch.tensor([
    [0.5, 0.3, 0.8, 0.2],
    [0.1, 0.9, 0.4, 0.6],
    [0.7, 0.2, 0.5, 0.9]
])

# Step 2: Create linear layer (4 inputs -> 2 outputs)
layer = nn.Linear(in_features=4, out_features=2)

# Step 3: Forward pass
output = layer(input_data)

# Step 4: Count parameters
total_params = sum(p.numel() for p in layer.parameters())

# Results
print("Input shape:", input_data.shape)   # [3, 4]
print("Output shape:", output.shape)      # [3, 2]
print("Total parameters:", total_params)  # 10

Input shape: torch.Size([3, 4])
Output shape: torch.Size([3, 2])
Total parameters: 10
