<a href="https://colab.research.google.com/github/wolfiee42/PyTorch-for-DeepLearning/blob/main/Introduction_to_PyTorch_and_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

zero_tensors = torch.zeros(2, 4)
print("Zero tensors: ")
print(zero_tensors)

one_tensors = torch.ones(3, 3)
print("One tensors: ")
print(one_tensors)

torch.manual_seed(42)

# create random tensor
random_tensors = torch.rand(2, 3)
print("Random tensor:")
print(random_tensors)

randn_tensor = torch.randn(2, 3)
print("Randn tensor")
print(randn_tensor)


# creating sequence
seq1 = torch.arange(10)
print("arrange(10): ", seq1)

# sequence with step
seq2 = torch.arange(2, 11, 2)
print("arange(2, 10, 2): ", seq2)


# float sequence
seq3 = torch.arange(0.0, 1.0, 0.2)
print("arange(0.0, 1.0, 0.2): ", seq3)

# linespace
linear = torch.linspace(0, 10, 5)
print("linspace(0, 10, 5): ", linear)


# centered
centered = torch.linspace(-1, 1, 7)
print("linspace(-1, 1, 7): ", centered)



## Tensor Attribute
# Shape

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.randn(2, 3, 4)

print("tensor_a shape: ", tensor_a.shape)
print("tensor_b shape: ", tensor_b.shape)


print("tensor_b dim 0: ", tensor_b.shape[0])
print("tensor_b dim 1: ", tensor_b.shape[1])
print("tensor_b dim 2: ", tensor_b.shape[2])

# alternative of shape method: size()
print("Tensor_a size:", tensor_a.size())


# Data Type
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print("Float tensor dtype:", float_tensor.dtype)

int_tensor = torch.tensor([1, 2, 3])
print("Int tensor dtype:", int_tensor.dtype)

double_tensor= torch.tensor([.0, 2.6], dtype=torch.float64)
print("Double tensor dtype:", double_tensor.dtype)

boolean_tensor = torch.tensor([True, False, False])
print("Boolean tensor dtype", boolean_tensor.dtype)


# Device
cpu_tensor = torch.tensor([1,2,3])
print("Device:", cpu_tensor.device)

if torch.cuda.is_available():
    gpu_tensor = torch.tensor([1, 2, 3], device='cuda')
    print("GPU Device:", gpu_tensor.device)

    cpu_to_gpu = cpu_tensor.to('cuda')
    print("moved to GPU:", cpu_to_gpu.device)
else:
    print("Cuda is not available - using CPU")


Zero tensors: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
One tensors: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Random tensor:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Randn tensor
tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])
arrange(10):  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange(2, 10, 2):  tensor([ 2,  4,  6,  8, 10])
arange(0.0, 1.0, 0.2):  tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])
linspace(0, 10, 5):  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
linspace(-1, 1, 7):  tensor([-1.0000e+00, -6.6667e-01, -3.3333e-01, -2.9802e-08,  3.3333e-01,
         6.6667e-01,  1.0000e+00])
tensor_a shape:  torch.Size([2, 3])
tensor_b shape:  torch.Size([2, 3, 4])
tensor_b dim 0:  2
tensor_b dim 1:  3
tensor_b dim 2:  4
Tensor_a size: torch.Size([2, 3])
Float tensor dtype: torch.float32
Int tensor dtype: torch.int64
Double tensor dtype: torch.float64
Boolean tensor dtype torch.bool
Devi